name: Run simulations DE

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0,3,6,9,12,15,18,21 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_simulations.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          pip install -r requirements_simulations.txt

      # /home/runner/work/simple-polls/simple-polls
      - name: gspread credentials 1
        run: |
          mkdir -p /home/runner/.config
          mkdir -p /home/runner/.config/gspread
      - name: gspread credentials 2
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'service_account.json'
          json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          dir: '../../../.config/gspread/'
          
      # - name: debug 1
      #   run: |-
      #     pwd
      #     ls /home/runner/
      #     ls /home/runner/.config/gspread/
      
      - name: Run simulations
        run: python simulations_de.py

      - name: gspread credentials 3
        run: |
          rm -r /home/runner/.config
 
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
  
