name: Update Odds CZ 2025

on:
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-odds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas gspread oauth2client
        
    - name: Run add_odds.py
      run: |
        cd cz-2025
        python add_odds.py
      env:
        # You'll need to add your Google Sheets service account credentials
        # as a repository secret named GOOGLE_SHEETS_CREDENTIALS
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        
    - name: Commit and push changes (if any)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-update odds data [skip ci]"
        git push
