name: Update Polymarket Spreads CZ 2025

on:
  # schedule:
    # Run every 1 hour
    # - cron: '3 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-polymarket:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas gspread oauth2client py_clob_client python-dotenv
        
    # Creates the directory where gspread looks for credentials by default
    - name: Create gspread config directory
      run: mkdir -p /home/runner/.config/gspread
        
    - name: Populate gspread credentials
      run: |
        echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > /home/runner/.config/gspread/service_account.json
        
    - name: Run add_polymarket_2.py
      env:
        POLYMARKET_PRIVATE_KEY: ${{ secrets.POLYMARKET_PRIVATE_KEY }}
        POLYMARKET_PROXY_ADDRESS: ${{ secrets.POLYMARKET_PROXY_ADDRESS }}
      run: python cz-2025/add_polymarket_2.py
